github:
  description: "Directives and KEYS files for ASF projects"
  homepage: https://infra.apache.org/
  labels:
    - pipenv

notifications:
  commits: notifications@infra.apache.org
  pullrequests: commits@infra.apache.org
  issues: private@infra.apache.org
