# This is the project-specific configuration for the ponymail project.
# It was last updated at Tue May 28 21:22:13 2024 by humbedooh@apache.org

committers_can_promote: true
committers_can_upload: true
notify: dev@ponymail.apache.org
require_vote: false
